version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: react-flask-webchat
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db
      - redis
    entrypoint: >
      sh -c "flask db upgrade && supervisord -c /etc/supervisor/conf.d/supervisord.conf"
  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

volumes:
  data:
  redis:
